[tox]
envlist = py
isolated_build = true

[testenv]
package = editable
deps =
    pytest
    pytest-cov
commands =
    pytest {tty:--color=yes} {posargs:--cov-report=html:{envtmpdir}/htmlcov/}

[testenv:pre-commit]
skip_install = true
deps = pre-commit
pass_env =
    {[testenv]pass_env}
    SKIP
commands = pre-commit run --all-files --show-diff-on-failure
